#!/bin/sh

name()
{
	grep -rn "project name" build.xml |
	sed 's/"//g' | cut -f2 -d'=' | cut -f1 -d' '
}

if [ -n "$1" ]; then
	if [ -n "$2" ]; then
		dst=$2
	else
		dst=$(basename $1)
	fi
	adb push "$1" /data/local/tmp/$dst
fi

echo "To add/replace test data invoke \"$(basename $0) <data>\""

adb shell am force-stop com.example.$(name)
adb shell am start com.example.$(name)/android.app.NativeActivity
