#!/bin/sh

target=$(grep "APP_PLATFORM" jni/Application.mk | cut -f2 -d'=')
if [ -z "$target" ]; then
	echo "jni/Application.mk does not specify target"
	exit 1
fi

android update project -p . -s -t $target
